### ISSUE TITLE
请问无法订阅实时行情，是正常的吗？

### ISSUE THREAD

**Issue by zhaole0451** [ruyisee/vnpy_qmt#5]
你好，请问，您的VNPYQMT中在使用过程中，无法订阅显示实时行情， 是正常的吗？

**Comment by ruyisee** [comment]
迅投MiniQMT是否启动，配置是否填写正确，有没有报什么错误信息

**Comment by ruyisee** [comment]
> 你好，请问，您的VNPYQMT中在使用过程中，无法订阅显示实时行情， 是正常的吗？

迅投MiniQMT是否启动，配置是否填写正确，有没有报什么错误信息

**Comment by zhaole0451** [comment]
感谢，找到问题的原因了，是需要在实盘时段才有数据显示。

**Comment by zhaole0451** [comment]
追加一个问题，在掉线重新打开VNPY后，原来挂单（未成交）的合约“委托号”变成了"None"内容，将导致无法撤单。
