### ISSUE TITLE
重启VNPY后，合约委托号为None后，如何处理

### ISSUE THREAD

**Issue by zhaole0451** [ruyisee/vnpy_qmt#6]
在掉线重新打开VNPY后，原来挂单（未成交）的合约“委托号”变成了"None"内容，将导致无法撤单。

**Comment by ruyisee** [comment]
本地生成的order_id重启以后会丢失. 这个问题在vnpy其他通道里也有，涉及到本地生成的id能不能上传。不是大问题 #7 已优化

**Comment by ruyisee** [comment]
更新一下版本， 0.3.1
